/*
 * Gurjit Singh
 * Friday December 6th - 2019
 * This program displays the encrypt and decrypt software
 */

/**
 *
 * @author gusin5788
 */
public class encryptionprogramfrm extends javax.swing.JFrame {

    /**
     * Creates new form encryptionprogramfrm
     */
    public encryptionprogramfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFirst = new javax.swing.JLabel();
        lblSecond = new javax.swing.JLabel();
        lblThird = new javax.swing.JLabel();
        lblFourth = new javax.swing.JLabel();
        lblFifth = new javax.swing.JLabel();
        txtFirst = new javax.swing.JTextField();
        txtSecond = new javax.swing.JTextField();
        txtThird = new javax.swing.JTextField();
        txtFourth = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();
        btnSecond = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirst.setFont(new java.awt.Font("NimbusRomDCY", 1, 18)); // NOI18N
        lblFirst.setText("ENCRYPT/DECRYPT SOFTWARE");
        jPanel1.add(lblFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lblSecond.setFont(new java.awt.Font("NimbusRomDCY", 0, 18)); // NOI18N
        lblSecond.setText("Enter a decrypted message and it will encrypted:");
        jPanel1.add(lblSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        lblThird.setFont(new java.awt.Font("NimbusRomDCY", 0, 18)); // NOI18N
        lblThird.setText("-----------------------------------------------------------------");
        jPanel1.add(lblThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 400, -1));

        lblFourth.setFont(new java.awt.Font("NimbusRomDCY", 0, 18)); // NOI18N
        lblFourth.setText("Enter an encrypted message and it will decrypted:");
        jPanel1.add(lblFourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        lblFifth.setFont(new java.awt.Font("NimbusRomDCY", 0, 18)); // NOI18N
        lblFifth.setText("-----------------------------------------------------------------");
        jPanel1.add(lblFifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        txtFirst.setFont(new java.awt.Font("NimbusRomDCY", 0, 18)); // NOI18N
        jPanel1.add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 390, -1));

        txtSecond.setFont(new java.awt.Font("NimbusRomDCY", 0, 18)); // NOI18N
        txtSecond.setText("Encrypted message will be displayed here:");
        jPanel1.add(txtSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 390, -1));

        txtThird.setFont(new java.awt.Font("NimbusRomDCY", 0, 18)); // NOI18N
        jPanel1.add(txtThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 390, -1));

        txtFourth.setFont(new java.awt.Font("NimbusRomDCY", 0, 18)); // NOI18N
        txtFourth.setText("Decrypted message will be displayed here:");
        jPanel1.add(txtFourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 390, -1));

        btnFirst.setFont(new java.awt.Font("NimbusRomDCY", 0, 18)); // NOI18N
        btnFirst.setText("Encrypt");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel1.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        btnSecond.setFont(new java.awt.Font("NimbusRomDCY", 0, 18)); // NOI18N
        btnSecond.setText("Decrypt");
        btnSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecondActionPerformed(evt);
            }
        });
        jPanel1.add(btnSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        String decMessage;
        String encMessage = "";
        char tempChar;
        int tempASCII;
        
        decMessage = txtFirst.getText();
        
        do {
            for (int i = 0; i < decMessage.length(); i = i + 1) {
            tempChar = decMessage.charAt(i);
            
            tempASCII = (int)tempChar;
            
            tempASCII = tempASCII + 3;
            
            tempChar = (char)tempASCII;
            
            encMessage = encMessage + tempChar;
            }
        } while (decMessage.length() > 31);
        
        txtSecond.setText(encMessage);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecondActionPerformed
        String encMessage;
        String decMessage = "";
        char tempChar;
        int tempASCII;
        
        encMessage = txtThird.getText();
        
        do {
            for (int i = 0; i < encMessage.length(); i = i + 1) {
            tempChar = encMessage.charAt(i);
            
            tempASCII = (int)tempChar;
            
            tempASCII = tempASCII - 3;
            
            tempChar = (char)tempASCII;
            
            decMessage = decMessage + tempChar;
            }
        } while (encMessage.length() > 31);
        
        txtFourth.setText(decMessage);
    }//GEN-LAST:event_btnSecondActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(encryptionprogramfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(encryptionprogramfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(encryptionprogramfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(encryptionprogramfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new encryptionprogramfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnSecond;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFifth;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblFourth;
    private javax.swing.JLabel lblSecond;
    private javax.swing.JLabel lblThird;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtFourth;
    private javax.swing.JTextField txtSecond;
    private javax.swing.JTextField txtThird;
    // End of variables declaration//GEN-END:variables
}
